[package]
name = "varflags"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitworks = { path = "../bitworks" }
quote = "*"
syn = { version = "*", features = ["full"] }
proc-macro2 = "*"
